name = "menu-app"
compatibility_date = "2026-05-11"

# D1 Database binding — update database_id after creating database
[[d1_databases]]
binding = "DB"
database_name = "menu-db"
database_id = "2caf2e16-1cab-4754-bfd3-13e05bd316a2"

[assets]
directory = "dist"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
